<?php

/**
 * Implements hook_menu()
 */
function listformat_example_menu() {
  return [
    'listformat-example-form' => [
      'page callback' => 'drupal_get_form',
      /* @see listformat_example_form() */
      'page arguments' => ['listformat_example_form'],
      'access arguments' => ['administer site configuration'],
      'type' => MENU_CALLBACK,
    ],
  ];
}

/**
 * @param array $form
 * @param array $form_state
 *
 * @return array
 */
function listformat_example_form(
  array $form,
  /** @noinspection PhpUnusedParameterInspection */ array $form_state
) {
  $form['plugin'] = listformat()->confGetForm([], t('List format'));

  return $form;
}

