<?php

use Drupal\listformat\Manager\LfManager;
use Drupal\renderkit\ListFormat\ListFormatInterface;

/**
 * Implements hook_views_api().
 *
 * @see listformat_views_plugins()
 */
function listformat_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * @return \Drupal\listformat\Manager\LfManager
 */
function listformat() {
  static $manager;
  return isset($manager)
    ? $manager
    : $manager = _listformat_create_manager();
}

/**
 * @return \Drupal\listformat\Manager\LfManager
 */
function _listformat_create_manager() {
  $lfHandlerMap = uniplugin()->interfaceGetHandlerMap(ListFormatInterface::class);
  return new LfManager($lfHandlerMap);
}
