<?php

use Drupal\listformat\LfConfigurator\LfConfigurator;

/**
 * Implements hook_views_api().
 *
 * @see listformat_views_plugins()
 */
function listformat_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * @return \Drupal\listformat\LfConfigurator\LfConfiguratorInterface
 */
function listformat() {
  static $manager;
  return isset($manager)
    ? $manager
    : $manager = LfConfigurator::create();
}
